name: puppet-lint scan

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  security:

    strategy:
      matrix:
        operating-system: [ubuntu-latest]

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: list
        run: ls

      - name: Scan
        continue-on-error: true
        run: bin/puppet-lint . --sarif > results.sarif

      #- name: puppet-lint
      #  uses: shaopeng-gh/puppet-lint-action@main
      #  with:
      #    output-file: 'results.sarif'

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: results.sarif

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
