name: puppet-lint scan

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  security:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Scan
        continue-on-error: true
        run: bin/puppet-lint . --sarif > results.sarif

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: results.sarif

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
